stages:
  json2df:
    cmd: python src/json2df.py
    deps:
    - data/NSFW
    - data/SFW
    - src/json2df.py
    outs:
    - data/NSFW.parquet
    - data/SFW.parquet
  qa_pairs:
    cmd: python src/qa_pairs.py
    deps:
    - data/NSFW.parquet
    - data/SFW.parquet
    - src/qa_pairs.py
    outs:
    - data/NSFW_qa.parquet
    - data/SFW_qa.parquet
